### ISSUE TITLE
Incorporate `pylint` with pre-commit

### ISSUE THREAD

**Issue by hugodahl** [adafruit/cookiecutter-adafruit-circuitpython#104]
Discussed during the weekly CP call that running pylint on local changes would be of value to library contributors. This would make the pre-commit process a "one-stop-shop" for running formatting, performing validations, etc. This mostly involves adding the steps to the **.pre-commit-config.yaml**, with some caveats (below).

One concern mentioned by @jepler during the call was that it adds a required tool as part of the execution environment - both for contributors as well as within the CI pipeline. @tannewt mentioned the possibility of there being a **requirements.txt** like file for development environments within pip, possibly **dev-requirements.txt**.

There was also a heads-up from @kattni to make sure that the revision value for the pre-commit hook can **NOT** be "latest" or "current". Rather, it **MUST** have a proper version/tag number, i.e. "v0.2".

Finally, part of the changes would be to the generated GitHub workflow (`/.github/workflows/build.yml`) and remove the calls to pylint, since they would be performed by pre-commit from within the generated **.pre-commit-config.yaml**.

Reference: [CircuitPython Weekly for 16 February 2021](https://docs.google.com/document/d/1CgGh2MkN5dY0VeqONvdY1h9bs13mZhzp1a4nYExQ4vg/)

**Comment by askpatrickw** [comment]
I'm listening to the weekly... when  you run pre-commit, it installs all the things it needs (you have to install pre-commit). For example you can see Black runs, but it is  not installed.


Here is the pre-commit config

```
cat .pre-commit-config.yaml
# SPDX-FileCopyrightText: 2020 Diego Elio Pettenò
#
# SPDX-License-Identifier: Unlicense

repos:
-   repo: https://github.com/python/black
    rev: 20.8b1
    hooks:
    - id: black
-   repo: https://github.com/fsfe/reuse-tool
    rev: v0.12.1
    hooks:
    - id: reuse
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
```

Here is the pre-commit run

```
(cp_base)  patrickwalters@Mac-mini  ~/code/adafruit/Adafruit_CircuitPython_AzureIoT   fix-24 ±  pre-commit run --all-files
black....................................................................Passed
reuse....................................................................Passed
Check Yaml...............................................................Passed
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
```

And I can't uninstall black because its not installed

```
(cp_base)  patrickwalters@Mac-mini  ~/code/adafruit/Adafruit_CircuitPython_AzureIoT   fix-24 ±  pip uninstall black
WARNING: Skipping black as it is not installed.
```

**Comment by jepler** [comment]
I've experimentally added this stanza to my community-bundle project's .pre-commit-config.yaml https://github.com/jepler/Jepler_CircuitPython_udecimal/pull/4:
```
-   repo: https://github.com/pycqa/pylint
    rev: pylint-2.6.0
    hooks:
    -   id: pylint
        name: lint (examples)
        types: [python]
        files: ^examples/
        args:
        - --disable=missing-docstring,invalid-name,bad-whitespace
    -   id: pylint
        name: lint (code)
        types: [python]
        exclude: "^(docs/|examples/|setup.py$)"
```
This doesn't delineate the files to check in quite the same way as the existing code (it works by excluding some files that should not be tested, instead of listing files to be selected), but it has the advantage that by using `repo:` it will install the requirements into a virtual environment.  Some easily detected problems might arise if the new check checks too many files.  Some hard to detect problems might arise if it checks too few.

**Comment by askpatrickw** [comment]
I made this similiar change in circup. I also moved the pre-commit as early as reasonable in the build.yml so it would fail earlier for PRs.

https://github.com/adafruit/circup/pull/85/files#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721

**Comment by kattni** [comment]
Done!
