### ISSUE TITLE
PyPI Credentials For New Library

### ISSUE THREAD

**Issue by woolseyj** [adafruit/cookiecutter-adafruit-circuitpython#145]
I am creating a new [library](https://github.com/WoolseyWorkshop/WoolseyWorkshop_CircuitPython_74HC165) to place into the CircuitPython Community Bundle but am having problems getting it distributed to PyPI as part of the GitHub Action release process.

I created a PyPI account along with a PyPI token.  I added the token name and password as **pypi_username** and **pypi_password** as GitHub repository secrets as seemed correct from the release.yml file.  Python packaging and distribution is new to me so I might need a little newbie help, which would be greatly appreciated.

**Comment by jposada202020** [comment]
@lesamouraipourpre . Hello could you help with this question, not familiar with the PyPI process as any of my libraries is in there, so I thought you could guide us here. Thanks

**Comment by woolseyj** [comment]
I also tried using "\_\_token\_\_" as the **pypi_username** and the actual token, beginning with pypi-, as the **pypi_password** as seen in various documentation and tutorials, but that did not work either.

**Comment by lesamouraipourpre** [comment]
As it stands your project will never upload to PyPI because it's name collides with the official Adafruit package. You can either try to PR it and merge to Adafruit/main or rename your `Repository` and change all the `PyPI` and `readthedocs` names inside the package to match the new name.
Possible names would be
* Community_CircuitPython_74HC165
* Woolsey_CircuitPython_74HC165
* Woolseyj_CircuitPython_74HC165 etc.


Instructions for Uploading to PyPI
======================
When you are signed in to PyPI go to https://pypi.org/manage/account/
About half way down the page there is a blue button `Add API token` which links to https://pypi.org/manage/account/token/
Select the scope at the bottom first
* If the package has never uploaded to PyPI it won't appear in the dropdown, just select 'Entire Account'. Enter a name of 'Temporary <PROJECT NAME>' You are going to remove it after the first sucessful upload.
* If the package has been uploaded to PyPI, select it from the dropdown. Enter a name that matches the PROJECT.

Click `Add Token` button at bottom
You will get something like the following (Note: this key has already been deleted)
<img width="611" alt="pypi1" src="https://user-images.githubusercontent.com/70200140/121440043-05c8b000-c97f-11eb-9df7-c90dbebe26ae.PNG">
I tend to keep this window open just in case, but copy the key now.

Go to your project on Github.
Select the `Settings` tab
Down the left edge, select `Secrets`
Towards the top right, click `New repository secret`

First, Name = `PYPI_USERNAME`, Value = `__token__`
Second, Name = `PYPI_PASSWORD`, Value = `pypi-Ag...` Paste in the correct value

Your Secrets page should look like this.

<img width="960" alt="pypi2" src="https://user-images.githubusercontent.com/70200140/121440353-a5863e00-c97f-11eb-8360-08b77dc1d9b0.PNG">

Trigger a push to PyPI by creating a release. From your project github page, click `Releases` at the right.
Click `Draft a new release` button and enter the details. The version number must have a MAJOR.MINOR.PATCH minimum format, eg `0.2.8` NOT `0.2`
Hopefully if everything worked, it will have pushed to PyPI.

**NOTE:** If you created a token with all-access to your user on PyPI, delete it now. Create a new one which is linked only to this project and update the `PYPI_PASSWORD` secret on Github

**Comment by jposada202020** [comment]
@lesamouraipourpre as always your info surpass my expectations. Thanks a lot

**Comment by woolseyj** [comment]
@lesamouraipourpre, thank you for the instructions, however, I am still a bit confused.

The name of the package I am trying to upload is WoolseyWorkshop_CircuitPython_74HC165, which should not interfere with the official Adafruit packages.  I believe there is some confusion due to the GitHub issue that @jposada202020 linked to where I originally created the Adafruit_CircuitPython_74HC165 library in the understanding that Adafruit would like to take it over to complement the existing Adafruit_CircuitPython_74HC595 library in the standard bundle.  See this [issue](https://github.com/adafruit/circuitpython/issues/4777).  The [library](https://github.com/WoolseyWorkshop/WoolseyWorkshop_CircuitPython_74HC165) link in my first comment of this request should point to the new WoolseyWorkshop_CircuitPython_74HC165 library which is the one I plan to add to the Community bundle and the one this issue request is for.

The PyPI process you presented is what I had followed, except I used a different API token name and I had accidentally used an invalid release tag in my last attempt.  I followed your process again this time using the name of "Temporary" as you suggested, and it worked.  Thank you.  However, once I created a new PyPI token limiting the scope and applied that token to the GitHub secret, it failed again.  I also don't understand why the package that WAS uploaded to PyPI has a release name of 0.1.0 when the GitHub tag that released it was 0.5.0.

**Comment by woolseyj** [comment]
I think I got it figured out.  The last one that failed with the project scope, failed for a different reason as shown in the GitHub Action log.  "File already exists. See https://pypi.org/help/#file-name-reuse for more information."

I made some minor comment updates to the library file, pushed it to GitHub, and created a new release.  The package pushed to PyPI with the proper version and I was able to install it with pip.

This is all new for me so thank you for pointing me in the right direction.  This cookiecutter template is awesome!

**Comment by lesamouraipourpre** [comment]
As you've found there is a restriction with PyPI accepting a new push of the same version number. There is a way to force it to update but it's usually easier to increase the patch number.
Also the very first creation of a PyPI release in Github Actions will use 0.1.0 if there has never been a tagged release before. There's a pending PR #146 that may have the side-effect of fixing that.

**Comment by jposada202020** [comment]
Good I followed the instructions here to add my CircuitPython-Styles library to PyPi and it works as described. I think we could close this issue. Thanks
