### ISSUE TITLE
Prefix or No Prefix specified is changing the library from prefix_cp_library to cp_org_library

### ISSUE THREAD

**Issue by askpatrickw** [adafruit/cookiecutter-adafruit-circuitpython#149]
I'm not sure if this is intentional or not, but if you specify a prefix you get a community bundle type name, and if you don't you get a circuitpython_org bundle type name.

## Prefix

cookiecutter cookiecutter-adafruit-circuitpython
Select target_bundle:
1 - Adafruit
2 - Community
Choose from 1, 2 [1]: 2
github_user []: askpatrickw
author_name: Patrickw
company []: Pimoroni
library_name: LTR765
library_description []: Magic !
library_keywords []: keys
library_prefix []: PREFIX
adafruit_pid []:
requires_bus_device []: n
requires_register []: n
other_requirements []: n
pypi_release [no]: n
sphinx_docs [no]: n

result: Prefix_CircuitPython_LTR765

## NO Prefix
cookiecutter cookiecutter-adafruit-circuitpython
Select target_bundle:
1 - Adafruit
2 - Community
Choose from 1, 2 [1]: 2
github_user []: myuser
author_name: My Name
company []:
library_name: library 2000
library_description []:
library_keywords []:
library_prefix []:
adafruit_pid []:
requires_bus_device []:
requires_register []:
other_requirements []:
pypi_release [no]:
sphinx_docs [no]:

result: CircuitPython_Org_library_2000

**Comment by kattni** [comment]
@FoamyGuy Can you look into this, please? Thank you!

**Comment by FoamyGuy** [comment]
@askpatrickw @kattni That behavior was intentional when I first implemented it around the time that we begun making the displayio widget repos in the CircuitPython org. #135 is where it was first added.  It turned out to a bit tricky since the "Org" ends up going between "CircuitPython" and the library name so it's not easily possible to "CircuitPython_Org" as a prefix without adding extra logic to remove the "CircuitPython" that would come after the prefix.

I am open to changing it though. I think my thought process was that folks would use their own name (or github username) as the prefix for personal libraries that end up in the community bundle.

Do we have a specific desired behavior in mind? 

Perhaps adding a 3rd option for the `target_bundle` question?
```
Select target_bundle:
1 - Adafruit
2 - Community
3 - CircuitPython Org
```
If `3` is selected then it could skip the prefix question if possible. If `2` is selected then it could not do anything differently based on whether a prefix is entered or not.

**Comment by askpatrickw** [comment]
Let's see if we agree on the segments of the name and what they are for (as I understand them and I could be wrong)

PREFIX_BUNDLE_LIBRARY

Prefix: User or Group Name (optional)
Bundle: Which Bundle this library is released in
Library: The name of the thing

@FoamyGuy Are you saying when the library is being distributed in the CircuitPython Org bundle that the PREFIX should never be added?

Overall though, I do think because the prefix is optional, changing the target bundle menu to include CP_ORG would be easier to understand \ follow as opposed to keying off the prefix value passed.

**Comment by FoamyGuy** [comment]
I agree with your prefix, bundle, library definition those are my understanding as well.

> @FoamyGuy Are you saying when the library is being distributed in the CircuitPython Org bundle that the PREFIX should never be added?

I believe this is the case yes. Since they are meant to be supported by the larger community and not any one individual I don't think it makes sense for an individual to use their name as the prefix i.e `Foamyguy_CircuitPython_Org_SomeLibrary` The only thing that seems like it would make sense as a prefix is "CircuitPython Org" but since that is already included it would make the name somewhat redundant i.e. `CircuitPython_Org_CircuitPython_SomeLibrary`

For the repos that have been [created already](https://github.com/circuitpython/) their names take the form `CircuitPython_Org_SomeLibrary` which follows the lack of prefix.

**Comment by askpatrickw** [comment]
OK, I'll make the change to add a 3rd option to the bundle choice and undo the logic where blank prefix == CP_org.

**Comment by FoamyGuy** [comment]
@askpatrickw I've started working on that change. Hoping to have a PR ready for it this weekend. 

It turned out to be a bit tricky due to limit on the length of filenames adding the logic for the 3rd option to the name of the library dir pushed us over the limit, I have a solution working with post gen hooks, but need to get some more testing done before I PR it.

**Comment by askpatrickw** [comment]
Awesome, I'll let you do it!

hmm.. all I did was add the option and change the folder name to 

`{% if cookiecutter.library_prefix %}{{ cookiecutter.library_prefix | capitalize }}{% endif %}{{cookiecutter.target_bundle}}_{{ cookiecutter.library_name|replace(" ", "_") | capitalize}}`

I was wondering if the library_name should be upper or capitalize in the folder name. Really only matters if you use a library name with a space.

**Comment by askpatrickw** [comment]
and cookiecutter.json

```
{
    "target_bundle": [
        "Adafruit",
        "CircuitPython_Org",
        "Community"
    ],
    "github_user": "{%- if cookiecutter.target_bundle == 'Adafruit' -%} adafruit {%- endif -%}",
    "author_name": null,
    "company": "{%- if cookiecutter.target_bundle == 'Adafruit' -%} Adafruit Industries {%- endif -%}",
    "library_name": null,
    "library_description": "",
    "library_keywords": "",
    "library_prefix": "{%- if cookiecutter.target_bundle == 'Adafruit' -%} adafruit {%- endif -%}",
    "adafruit_pid": "",
    "requires_bus_device": "",
    "requires_register": "",
    "other_requirements": "",
    "pypi_release": "{%- if cookiecutter.target_bundle == 'Adafruit' -%} yes {%- else -%} no {%- endif -%}",
    "sphinx_docs":  "{%- if cookiecutter.target_bundle == 'Adafruit' -%} yes {%- else -%} no {%- endif -%}",
    "_extensions": ["jinja2.ext.do"],
    "_copy_without_render": ["*.github/*"]
}
```
